{
  config,
  lib,
  pkgs,
  ...
}: let
  uploadLocation = "/mnt/services/immich/library";
  dbDataLocation = "/var/lib/oci/immich/pg";
  tz = "America/Bogota";
  immichVersion = "v2.7.5";
  dbUsername = "postgres";
  dbDatabaseName = "immich";
  cfg = config.frost.oci.immich;
in {
  options.frost.oci.immich = {
    enable = lib.mkEnableOption "Immich";
    sopsFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "SOPS file containing immich environment secrets.";
    };
  };

  config = lib.mkIf cfg.enable {
    sops.secrets.immich = lib.mkIf (cfg.sopsFile != null) {
      sopsFile = cfg.sopsFile;
      format = "yaml";
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-immich-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };

    systemd.services = {
      "podman-immich_machine_learning" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after =
          lib.optionals (cfg.sopsFile != null) ["sops-nix.service"]
          ++ [
            "podman-network-immich_default.service"
            "podman-volume-immich_model-cache.service"
          ];
        requires = [
          "podman-network-immich_default.service"
          "podman-volume-immich_model-cache.service"
        ];
        partOf = [
          "podman-compose-immich-root.target"
        ];
        upheldBy = [
          "podman-network-immich_default.service"
          "podman-volume-immich_model-cache.service"
        ];
        wantedBy = [
          "podman-compose-immich-root.target"
        ];
      };

      "podman-immich_postgres" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after =
          lib.optionals (cfg.sopsFile != null) ["sops-nix.service"]
          ++ [
            "podman-network-immich_default.service"
          ];
        requires = [
          "podman-network-immich_default.service"
        ];
        partOf = [
          "podman-compose-immich-root.target"
        ];
        upheldBy = [
          "podman-network-immich_default.service"
        ];
        wantedBy = [
          "podman-compose-immich-root.target"
        ];
      };

      "podman-immich_redis" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after =
          lib.optionals (cfg.sopsFile != null) ["sops-nix.service"]
          ++ [
            "podman-network-immich_default.service"
          ];
        requires = [
          "podman-network-immich_default.service"
        ];
        partOf = [
          "podman-compose-immich-root.target"
        ];
        upheldBy = [
          "podman-network-immich_default.service"
        ];
        wantedBy = [
          "podman-compose-immich-root.target"
        ];
      };

      "podman-immich_server" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after =
          lib.optionals (cfg.sopsFile != null) ["sops-nix.service"]
          ++ [
            "podman-network-immich_default.service"
          ];
        requires = [
          "podman-network-immich_default.service"
        ];
        partOf = [
          "podman-compose-immich-root.target"
        ];
        upheldBy = [
          "podman-immich_postgres.service"
          "podman-immich_redis.service"
          "podman-network-immich_default.service"
        ];
        wantedBy = [
          "podman-compose-immich-root.target"
        ];
      };

      # Networks
      "podman-network-immich_default" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f immich_default";
        };
        script = ''
          podman network inspect immich_default || podman network create immich_default
        '';
        partOf = ["podman-compose-immich-root.target"];
        wantedBy = ["podman-compose-immich-root.target"];
      };

      # Volumes
      "podman-volume-immich_model-cache" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect immich_model-cache || podman volume create immich_model-cache
        '';
        partOf = ["podman-compose-immich-root.target"];
        wantedBy = ["podman-compose-immich-root.target"];
      };
    };

    virtualisation.oci-containers.containers = {
      "immich_server" = {
        image = "ghcr.io/immich-app/immich-server:${immichVersion}";
        autoStart = true;
        autoRemoveOnStop = false;
        environmentFiles = lib.optionals (cfg.sopsFile != null) [
          config.sops.secrets.immich.path
        ];
        environment = {
          "UPLOAD_LOCATION" = uploadLocation;
          "DB_DATA_LOCATION" = dbDataLocation;
          "TZ" = tz;
          "IMMICH_VERSION" = immichVersion;
          "DB_USERNAME" = dbUsername;
          "DB_DATABASE_NAME" = dbDatabaseName;
        };
        volumes = [
          "${uploadLocation}:/data:rw"
          "/etc/localtime:/etc/localtime:ro"
        ];
        ports = [
          "2283:2283/tcp"
        ];
        dependsOn = [
          "immich_redis"
          "immich_postgres"
        ];
        log-driver = "journald";
        extraOptions = [
          "--restart=unless-stopped"
          "--health-cmd=none"
          "--health-interval=30s"
          "--health-timeout=5s"
          "--health-retries=3"
          "--health-start-period=5s"
          "--network-alias=immich-server"
          "--network=immich_default"
        ];
      };

      "immich_machine_learning" = {
        image = "ghcr.io/immich-app/immich-machine-learning:${immichVersion}";
        autoStart = true;
        autoRemoveOnStop = false;
        environmentFiles = lib.optionals (cfg.sopsFile != null) [
          config.sops.secrets.immich.path
        ];
        environment = {
          "UPLOAD_LOCATION" = uploadLocation;
          "DB_DATA_LOCATION" = dbDataLocation;
          "TZ" = tz;
          "IMMICH_VERSION" = immichVersion;
          "DB_USERNAME" = dbUsername;
          "DB_DATABASE_NAME" = dbDatabaseName;
        };
        volumes = ["immich-model-cache:/cache:rw"];
        log-driver = "journald";
        extraOptions = [
          "--restart=unless-stopped"
          "--health-cmd=none"
          "--health-interval=30s"
          "--health-timeout=5s"
          "--health-retries=3"
          "--health-start-period=5s"
          "--network-alias=immich-machine-learning"
          "--network=immich_default"
        ];
      };

      "immich_redis" = {
        image = "docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9";
        autoStart = true;
        autoRemoveOnStop = false;
        environmentFiles = lib.optionals (cfg.sopsFile != null) [
          config.sops.secrets.immich.path
        ];
        environment = {
          "UPLOAD_LOCATION" = uploadLocation;
          "DB_DATA_LOCATION" = dbDataLocation;
          "TZ" = tz;
          "IMMICH_VERSION" = immichVersion;
          "DB_USERNAME" = dbUsername;
          "DB_DATABASE_NAME" = dbDatabaseName;
        };
        log-driver = "journald";
        extraOptions = [
          "--restart=unless-stopped"
          "--health-cmd=redis-cli ping || exit 1"
          "--health-interval=30s"
          "--health-timeout=5s"
          "--health-retries=3"
          "--health-start-period=5s"
          "--network-alias=redis"
          "--network=immich_default"
        ];
      };

      "immich_postgres" = {
        image = "ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0";
        autoStart = true;
        autoRemoveOnStop = false;
        environmentFiles = lib.optionals (cfg.sopsFile != null) [
          config.sops.secrets.immich.path
        ];
        environment = {
          "UPLOAD_LOCATION" = uploadLocation;
          "DB_DATA_LOCATION" = dbDataLocation;
          "TZ" = tz;
          "IMMICH_VERSION" = immichVersion;
          "DB_USERNAME" = dbUsername;
          "DB_DATABASE_NAME" = dbDatabaseName;
          "POSTGRES_USER" = dbUsername;
          "POSTGRES_DB" = dbDatabaseName;
          "POSTGRES_INITDB_ARGS" = "--data-checksums";
        };
        volumes = [
          "${dbDataLocation}:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--shm-size=128mb"
          "--health-cmd=none"
          "--health-interval=30s"
          "--health-start-period=5s"
          "--health-retries=3"
          "--health-timeout=5s"
          "--network-alias=database"
          "--network=immich_default"
        ];
      };
    };
  };
}
