# ~/.config/hyprpolkitagent/hyprpolkitagent.conf

general {
    password_field_width = 340      # Width of the password box in pixels
    window_width = 520              # Total width of the agent window
    window_height = 440             # Total height of the agent window
    show_details = true             # Toggle whether to show action details by default
}
